services:
  php_apache:
    container_name: php_apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - /tmp:/tmp
    ports:
      - "8090:80"
    environment:
      DATABASE_URL: 'mysql://symfony:symfony@mysql:3306/formasphere'
      MERCURE_URL: 'http://mercure/.well-known/mercure'
      MERCURE_PUBLIC_URL: 'http://localhost:1337/.well-known/mercure'
      MERCURE_JWT_SECRET: symfonyMercureSuperSecret2025Super!
    deploy:
      resources:
        limits:
          memory: 512M

  mysql:
    container_name: mysql_1
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: formasphere
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    container_name: adminer_1
    image: adminer
    ports:
      - "8081:8080"

  mercure:
    container_name: mercure_hub
    image: dunglas/mercure
    restart: always
    environment:
      MERCURE_JWT_COOKIE_NAME: 'mercureAuthorization'
      MERCURE_PUBLISHER_JWT_KEY: symfonyMercureSuperSecret2025Super!
      MERCURE_SUBSCRIBER_JWT_KEY: symfonyMercureSuperSecret2025Super!
      MERCURE_CORS_ALLOWED_ORIGINS: 'http://localhost:8090,http://localhost:1337'
      MERCURE_ALLOW_ANONYMOUS: '1'
      MERCURE_PUBLISH_ALLOWED_ORIGINS: '*'
      SERVER_NAME: ':80'
      DEBUG: '1'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8090
    ports:
      - "1337:80"


volumes:
  mysql-data:

