version: '3.7'

services:
  php_apache:
    container_name: php_apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8090:80"
    environment:
      DATABASE_URL: mysql://symfony:symfony@mysql:3306/formasphere

  mysql:
    container_name: mysql_1
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: formasphere
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    container_name: adminer_1
    image: adminer
    ports:
      - "8081:8080"

volumes:
  mysql-data:
